plugins {
    id 'fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
}

version = "${minecraft_version}-${mod_version}+fabric"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    mods {
        "fabric" {
            sourceSet sourceSets.main
        }
    }
    accessWidenerPath = file("src/main/resources/umapyoidelight.accesswidener")
}


repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url = "https://cursemaven.com"
    }
    maven {
        name = "Ladysnake Mods"
        url = "https://maven.ladysnake.org/releases"
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/releases/"
    }
    maven {
        name = "Quilt"
        url = "https://maven.quiltmc.org/repository/release/"
    }
    maven {
        name = "Cloth"
        url = "https://maven.shedaniel.me/"
    }
    maven {
        url = "https://mvn.devos.one/releases/"
    }
    maven {
        name = "JamiesWhiteShirt"
        url = "https://maven.jamieswhiteshirt.com/libs-release/"
    }
    maven {
        name = "Cassian's Maven"
        url = 'https://maven.cassian.cc'
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation "curse.maven:jei-238222:6600309" //JEI
    modImplementation "me.shedaniel.cloth:cloth-config-fabric:11.1.136"
    modImplementation "curse.maven:appleskin-248787:7517366" //Appleskin

    modImplementation "curse.maven:modmenu-308702:5162837"
    modImplementation "curse.maven:configured-457570:5180902"

    modImplementation "curse.maven:yacl-667299:6336639" //YACL
    modImplementation "org.quiltmc.parsers:json:0.2.1" //YACL dependencies
    modImplementation "org.quiltmc.parsers:gson:0.2.1"

    modImplementation "maven.modrinth:x1Rd7p5W:qa34Gjtf" //Umapyoi Fabricated
    modImplementation "curse.maven:owo-lib-532610:4749199" // owo-lib
    modImplementation "dev.emi:trinkets:3.7.1"// Trinkets
    modImplementation("vectorwing:FarmersDelight:1.20.1-2.5.7+refabricated") {
        exclude(group: "net.fabricmc")
    } // Farmer's Delight


}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 17
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
